### ISSUE TITLE
mountcifs lead reboot

### ISSUE THREAD

**Issue by armgong** [divx118/cifs#4]
on samsung chromebook2 13.3 (arm) , chromeos os dev version 41 ,repack kernel with @DennisLfromGA  enable-vmx.sh script. but when mountcifs chromebook reboot.

there is log 
 sudo cat /dev/pstore/console-ramoops

[  529.921521] Chromium OS LSM: init_module locking-ignored module="/usr/local/modules/armhfp_3.8.11/md4.ko" pid=20490 cmdline="insmod ../modules/armhfp_3.8.11/md4.ko"
[  534.159938] Chromium OS LSM: init_module locking-ignored module="/usr/local/modules/armhfp_3.8.11/cifs.ko" pid=20497 cmdline="insmod ../modules/armhfp_3.8.11/cifs.ko"
[ 1083.117047] Unable to handle kernel paging request at virtual address 000b0050
[ 1083.117059] pgd = ee804000
[ 1083.117067] [000b0050] *pgd=00000000
[ 1083.117081] Internal error: Oops: 5 [#1] SMP ARM
[ 1083.117090] Modules linked in: cifs md4 hidp nls_iso8859_1 nls_cp437 vfat fat i2c_dev uinput uvcvideo videobuf2_vmalloc rfcomm sbs_battery isl29018(C) btmrvl_sdio btmrvl bluetooth zram(C) zsmalloc(C) rtc_s3c fuse nf_conntrack_ipv6 nf_defrag_ipv6 ip6table_filter ip6_tables mwifiex_sdio mwifiex cfg80211 joydev ppp_async ppp_generic slhc tun
[ 1083.117243] CPU: 1    Tainted: G         C    (3.8.11 #1)
[ 1083.117256] PC is at strnlen+0x20/0x38
[ 1083.117281] LR is at cifs_get_volume_info+0xd8/0x1448 [cifs]
[ 1083.117290] pc : [<c030bfac>]    lr : [<bf214d7c>]    psr: 80000013
[ 1083.117290] sp : ec94ddb8  ip : ec94ddc8  fp : ec94ddc4
[ 1083.117298] r10: 000b004f  r9 : 00000000  r8 : ed437e40
[ 1083.117305] r7 : 000b0050  r6 : ef3fe000  r5 : ed328c00  r4 : ed328c00
[ 1083.117312] r3 : 000b0050  r2 : 000b0050  r1 : 000b005f  r0 : 000b0050
[ 1083.117320] Flags: Nzcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
[ 1083.117328] Control: 10c5387d  Table: 4e80406a  DAC: 00000015
[ 1083.117336] Process mount (pid: 21920, stack limit = 0xec94c240)
[ 1083.117343] Stack: (0xec94ddb8 to 0xec94e000)
[ 1083.117351] dda0:                                                       ec94de54 ec94ddc8
[ 1083.117359] ddc0: bf214d7c c030bf98 c0721064 271ae517 ec94de2c 000080d0 ed328c14 00000000
[ 1083.117368] dde0: c0b7ab80 00000000 00000000 002c0000 ec94de84 ec94de00 c01c28ec c01c2244
[ 1083.117377] de00: 00000000 00000041 c0b7a100 00000000 ed23b280 ec94de64 c0b2a314 c01d87a0
[ 1083.117385] de20: ec94de9c ec94de30 c01d87a0 00000000 ef3fe000 ed437e40 ed437e40 bf23f010
[ 1083.117393] de40: 00000000 c0b35b1c ec94dea4 ec94de58 bf208c04 bf214cb0 000012c0 c01c2eec
[ 1083.117402] de60: c1132000 ef3fe000 e8b393c0 00000000 ed437e40 bf23f010 ec94de94 ef3fe000
[ 1083.117410] de80: 00000000 e9000000 ed437e40 bf23f010 00000000 c0b35b1c ec94ded4 ec94dea8
[ 1083.117418] dea0: c01fc35c bf208bbc c0214d20 c01d88c4 ed437e40 e8b393c0 00000000 ef3fe000
[ 1083.117427] dec0: bf23f010 00000000 ec94defc ec94ded8 c0214f84 c01fc2e8 ef3fe000 00000020
[ 1083.117435] dee0: 00000000 ed437e40 ef3fe000 bf23f010 ec94df5c ec94df00 c021722c c0214f38
[ 1083.117443] df00: ef3fe000 00000000 c0b28bc8 ed4375c0 ec94df70 e9ae1190 e9cced10 ec94df28
[ 1083.117451] df20: c01c2eec c01da47c ec94df5c 271ae517 c0216b40 00000000 ec519000 c0b28bc8
[ 1083.117460] df40: c0ed0000 b85f59f8 b85f5990 b85f59b0 ec94dfa4 ec94df60 c02175ec c0216c58
[ 1083.117468] df60: ef3fe000 c063a4f8 ed4375c0 ed437e40 ef3fe000 271ae517 ec94c000 b85f59f8
[ 1083.117476] df80: 00000000 b85f59f8 00000015 c0106224 ec94c000 00000000 00000000 ec94dfa8
[ 1083.117484] dfa0: c0106000 c0217550 b85f59f8 00000000 b85f5990 b85f59b0 b85f5980 c0ed0000
[ 1083.117493] dfc0: b85f59f8 00000000 b85f59f8 00000015 be82b6f8 b85f5980 b6f9d9d0 b6fd7dc0
[ 1083.117501] dfe0: b6f9dfc0 be82b430 b6f7477f b6f19a78 600f0030 b85f5990 00000000 00000000
[ 1083.117507] Backtrace:
[ 1083.117534] [<c030bfac>] (strnlen+0x20/0x38) from [<bf214d7c>] (cifs_get_volume_info+0xd8/0x1448 [cifs])
[ 1083.117577] [<bf214d7c>] (cifs_get_volume_info+0xd8/0x1448 [cifs]) from [<bf208c04>] (cifs_do_mount+0x54/0x438 [cifs])
[ 1083.117600] [<bf208c04>] (cifs_do_mount+0x54/0x438 [cifs]) from [<c01fc35c>] (mount_fs+0x80/0x178)
[ 1083.117613] [<c01fc35c>] (mount_fs+0x80/0x178) from [<c0214f84>] (vfs_kern_mount+0x58/0xd4)
[ 1083.117626] [<c0214f84>] (vfs_kern_mount+0x58/0xd4) from [<c021722c>] (do_mount+0x5e0/0x8f8)
[ 1083.117637] [<c021722c>] (do_mount+0x5e0/0x8f8) from [<c02175ec>] (sys_mount+0xa8/0xf4)
[ 1083.117650] [<c02175ec>] (sys_mount+0xa8/0xf4) from [<c0106000>] (ret_fast_syscall+0x0/0x30)
[ 1083.117661] Code: e1a02000 e1520001 e1a03002 0a000003 (e5d3c000) 
[ 1083.117671] ---[ end trace fabf62d2d1fd202a ]---
[ 1083.118787] Kernel panic - not syncing: Fatal exception
[ 1083.118802] CPU0: stopping
[ 1083.118838] Backtrace:
[ 1083.118885] [<c010d18c>] (unwind_backtrace+0x0/0x110) from [<c063651c>] (dump_stack+0x28/0x30)
[ 1083.118935] [<c063651c>] (dump_stack+0x28/0x30) from [<c010bb74>] (handle_IPI+0xe0/0x15c)
[ 1083.118980] [<c010bb74>] (handle_IPI+0xe0/0x15c) from [<c0100410>] (gic_handle_irq+0x68/0x70)
[ 1083.119021] [<c0100410>] (gic_handle_irq+0x68/0x70) from [<c0105c00>] (__irq_svc+0x40/0x50)
[ 1083.119066] Exception stack(0xc0b01eb0 to 0xc0b01ef8)
[ 1083.119100] 1ea0:                                     c0b01ef8 000000fc 2e392f10 000000fc
[ 1083.119142] 1ec0: c003e3f8 00000000 2e18f53a 000000fc 00000000 c0b30e68 c0b7b670 c0b01f2c
[ 1083.119186] 1ee0: 00000006 c0b01ef8 c01669b0 c04d71e8 00000013 ffffffff
[ 1083.119231] [<c0105c00>] (__irq_svc+0x40/0x50) from [<c04d71e8>] (cpuidle_wrap_enter+0x58/0xa4)
[ 1083.119274] [<c04d71e8>] (cpuidle_wrap_enter+0x58/0xa4) from [<c04d68c0>] (cpuidle_enter_tk+0x14/0x1c)
[ 1083.119322] [<c04d68c0>] (cpuidle_enter_tk+0x14/0x1c) from [<c04d6cc0>] (cpuidle_enter_state+0x24/0x68)
[ 1083.119368] [<c04d6cc0>] (cpuidle_enter_state+0x24/0x68) from [<c04d6e80>] (cpuidle_idle_call+0x17c/0x260)
[ 1083.119412] [<c04d6e80>] (cpuidle_idle_call+0x17c/0x260) from [<c0106e04>] (cpu_idle+0xa4/0x104)
[ 1083.119460] [<c0106e04>] (cpu_idle+0xa4/0x104) from [<c0631d58>] (rest_init+0x6c/0x84)
[ 1083.119500] [<c0631d58>] (rest_init+0x6c/0x84) from [<c0a00924>] (start_kernel+0x370/0x3dc)
[ 1083.119544] CPU3: stopping
[ 1083.119575] Backtrace:
[ 1083.119611] [<c010d18c>] (unwind_backtrace+0x0/0x110) from [<c063651c>] (dump_stack+0x28/0x30)
[ 1083.119648] [<c063651c>] (dump_stack+0x28/0x30) from [<c010bb74>] (handle_IPI+0xe0/0x15c)
[ 1083.119685] [<c010bb74>] (handle_IPI+0xe0/0x15c) from [<c0100410>] (gic_handle_irq+0x68/0x70)
[ 1083.119718] [<c0100410>] (gic_handle_irq+0x68/0x70) from [<c0105c00>] (__irq_svc+0x40/0x50)
[ 1083.119751] Exception stack(0xef14dee8 to 0xef14df30)
[ 1083.119783] dee0:                   ef14df30 000000fc 2e395b02 000000fc c00593f8 00000000
[ 1083.119820] df00: 2e1785b6 000000fc 00000000 c0b30e68 c0b7b670 ef14df64 00000006 ef14df30
[ 1083.119850] df20: c01669b0 c04d71e8 00000013 ffffffff
[ 1083.119883] [<c0105c00>] (__irq_svc+0x40/0x50) from [<c04d71e8>] (cpuidle_wrap_enter+0x58/0xa4)
[ 1083.119922] [<c04d71e8>] (cpuidle_wrap_enter+0x58/0xa4) from [<c04d68c0>] (cpuidle_enter_tk+0x14/0x1c)
[ 1083.119957] [<c04d68c0>] (cpuidle_enter_tk+0x14/0x1c) from [<c04d6cc0>] (cpuidle_enter_state+0x24/0x68)
[ 1083.119993] [<c04d6cc0>] (cpuidle_enter_state+0x24/0x68) from [<c04d6e80>] (cpuidle_idle_call+0x17c/0x260)
[ 1083.120032] [<c04d6e80>] (cpuidle_idle_call+0x17c/0x260) from [<c0106e04>] (cpu_idle+0xa4/0x104)
[ 1083.120071] [<c0106e04>] (cpu_idle+0xa4/0x104) from [<c0633694>] (secondary_start_kernel+0x10c/0x130)
[ 1083.120108] [<c0633694>] (secondary_start_kernel+0x10c/0x130) from [<20632c28>] (0x20632c28)
[ 1083.120141] CPU2: stopping
[ 1083.120155] Backtrace:
[ 1083.120176] [<c010d18c>] (unwind_backtrace+0x0/0x110) from [<c063651c>] (dump_stack+0x28/0x30)
[ 1083.120193] [<c063651c>] (dump_stack+0x28/0x30) from [<c010bb74>] (handle_IPI+0xe0/0x15c)
[ 1083.120210] [<c010bb74>] (handle_IPI+0xe0/0x15c) from [<c0100410>] (gic_handle_irq+0x68/0x70)
[ 1083.120228] [<c0100410>] (gic_handle_irq+0x68/0x70) from [<c0105c00>] (__irq_svc+0x40/0x50)
[ 1083.120241] Exception stack(0xef14bee8 to 0xef14bf30)
[ 1083.120256] bee0:                   ef14bf30 000000fc 2e3944df 000000fc c00503f8 00000000
[ 1083.120271] bf00: 2e17a66d 000000fc 00000000 c0b30e68 c0b7b670 ef14bf64 00000006 ef14bf30
[ 1083.120284] bf20: c01669b0 c04d71e8 00000013 ffffffff
[ 1083.120302] [<c0105c00>] (__irq_svc+0x40/0x50) from [<c04d71e8>] (cpuidle_wrap_enter+0x58/0xa4)
[ 1083.120320] [<c04d71e8>] (cpuidle_wrap_enter+0x58/0xa4) from [<c04d68c0>] (cpuidle_enter_tk+0x14/0x1c)
[ 1083.120337] [<c04d68c0>] (cpuidle_enter_tk+0x14/0x1c) from [<c04d6cc0>] (cpuidle_enter_state+0x24/0x68)
[ 1083.120355] [<c04d6cc0>] (cpuidle_enter_state+0x24/0x68) from [<c04d6e80>] (cpuidle_idle_call+0x17c/0x260)
[ 1083.120374] [<c04d6e80>] (cpuidle_idle_call+0x17c/0x260) from [<c0106e04>] (cpu_idle+0xa4/0x104)
[ 1083.120391] [<c0106e04>] (cpu_idle+0xa4/0x104) from [<c0633694>] (secondary_start_kernel+0x10c/0x130)
[ 1083.120408] [<c0633694>] (secondary_start_kernel+0x10c/0x130) from [<20632c28>] (0x20632c28)
[ 1083.120430] CPU1 PC: <c011c8a8> exynos5_panic_notify+0x64/0xbc

**Comment by divx118** [comment]
Is this something that worked before for you? So maybe related to newer kernel source of chrome.

**Comment by armgong** [comment]
it indeed worked before, but after Sunday chromeos update it fails,

**Comment by divx118** [comment]
Thanks I see if I can build some new ones. However it can take some time.

**Comment by divx118** [comment]
Ok, this could also be reproduced on x86_64 3.8.11 kernel. Updated the modules with newly build ones from recent source, also updated the tar file. Still have to rebuild the modules for other kernel versions.  
@armgong Could you please try with the new modules and see if it works for you now and report back. Thanks in advance for your help.

**Comment by armgong** [comment]
problem solved, thank you very much
