### ISSUE TITLE
Fails with lsm Directory nonexistent

### ISSUE THREAD

**Issue by nice1bruvva** [divx118/cifs#5]
Hi
Thanks for all your hard work on implementing CIFS in Chromeos.. Ive been using this for a month or so and it worked perfectly. A few days ago it stopped working and I now get the following errors in terminal

chmod: cannot access '/sys/module/lsm/parameters/module_locking': No such file or directory
/usr/local/bin/mountcifs: 10: /usr/local/bin/mountcifs: cannot create /sys/module/lsm/parameters/module_locking: Directory nonexistent
insmod: ERROR: could not insert module /usr/local/modules/x86_64_3.8.11/cifs.ko: Operation not permitted

Is there anyway to fix it?

**Comment by divx118** [comment]
Yep, the sysfs path is removed from chromeos. You will need to disable module_locking by changing the kernel flags. I wrote a [script](https://github.com/divx118/crouton-packages/blob/master/change-kernel-flags) for that to make it easy. The script also allows you to revert the changes.  
Note: This script will disable verified boot and needs to be executed everytime you have a chromeos update. 
Open a cros shell and follow on screen instructions:
```
$ cd ~/Downloads
$ wget https://raw.githubusercontent.com/divx118/crouton-packages/master/change-kernel-flags
$ sudo sh ~/Downloads/change-kernel-flags
```
When running `sudo sh ~/Downloads/change-kernel-flags -h` it will give you the usage. When you want to revert the changes so put back a backup kernel use -r
`sudo sh ~/Downloads/change-kernel-flags -r`

For more info on why the sysfs is removed see https://github.com/dnschneid/crouton/issues/1278

**Comment by divx118** [comment]
Oh forgot something you will need to comment out the lines in the mountcifs script that contain `/sys/module/lsm/parameters/module_locking` I will soon fix this.

**Comment by nice1bruvva** [comment]
Hi Maurice
Thanks for your help..  I have run your script and confirmed module locking is off using cat.
I also commented out the lsm lines from the script.
Unfortunately, it now crashes when it runs mountcifs start..
I think it gets as far as loading the modules but can't be sure as it restarts straight away

Any ideas?

**Comment by divx118** [comment]
Which kernel/architecture do you have? `uname -r`. I probably need to rebuild the modules.

**Comment by nice1bruvva** [comment]
I have 3.8.11
I managed to insmod cifs.ko manually.. When I tried to mount the share it crashed so I think its something to do with the module in the kernel,,

**Comment by nice1bruvva** [comment]
full uname output
Linux localhost 3.8.11 #1 SMP Sat Mar 7 06:52:13 PST 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by divx118** [comment]
Ok, thanks same kernel as mine, so should  be easy to replicate for me. What I said, I think I need to rebuild the modules. Kernels have changed a lot lately.

**Comment by aetheon** [comment]
@divx118 Got a system crash with x86_64_3.10.18 modules.

**Comment by samuarl** [comment]
> Got a system crash with x86_64_3.10.18 modules.

I was also getting a kernel panic when loading the cifs module on x86_64_3.10.18. Recompiling from latest source along with module_locking kernel flags has resolved it for me.

**Comment by divx118** [comment]
@samuarl Thanks for letting it know. I will rebuild all the modules this weekend.

**Comment by divx118** [comment]
Ok, kernels for x86_64_3.8.11 are updated and tested by me. Also changed the script and removed sysfs lines and put in a warning that the kernel flag must be changed if it isn't already done.
Rest of the kernel modules will soon follow.

**Comment by divx118** [comment]
All modules are updated. Added new modules for x86_64 3.14.0 kernel (New pixel i7). Adjusted the README.md on how to disable module_locking. If there are any issues with the modules, you can open a new issue. I am closing this one for now.
