### ISSUE TITLE
Unable to mount to use in chroot

### ISSUE THREAD

**Issue by VeronicaEC** [divx118/cifs#7]
Hello, i've been trying to make this work for hours (days) with no luck.
* I have setup ./etc/fstab and changed device name, mount point, username and password. (even though in the readme doesn't mention to change the mount point i figured it out and also permission changes suggested by another user has not been applied, so it is still 0777)
* The mount point ended up like this: ~/Downloads/NO_TOCAR/NASdrive as i don't want to use an external usb drive or sdcard to mount it. The path mentioned exists and i triple verified the directory names.
* Then as per the instructions entered chroot: $ sudo enter-chroot
* Then in another windows opened a crosh shell and typed: $ sudo mountcifs start
Both modules cifs.ko and md4.ko loaded successfully but the mount FAILED, it says Mount: mount point ~/Downloads/NO_TOCAR/NASdrive does not exist

I also tried with just ~/Downloads path and same thing it says mount point does not exist.

My chroot is Xenial LXDE with xorg and extension targets (not using xiwi as i need hw acceleration)

PS: If any of you guys have all modules: autofs, cifs and nfs for kernel 3.8.11 x86_64 and Ubuntu Xenial please, please share with me. I don't have enough space in my chromebox and knowledge to build them.

Thanks in advance!

**Comment by divx118** [comment]
Sorry for not coming back to you earlier. I also read the mail, but am a little busy. First of all you will need to specify the full path, so replace the "~" with /home/chronos/user. However if you mount it on top of /home/chronos/user/Downloads/<your mountpoint> it won't show up in the files app and also like mentioned in the README.md with the bind and make-shared commands I couldn't get it to show up in the chroot. (I will update the README.md and remove that until we have a working solution). I always used an external device like a SD-card or USB stick to mount it on. This will show it in the files app and in the chroot. 

The cifs modules you can also use in your chroot. My mountcifs script loads them when you start the script and unloads them when execute the script with stop. However you can just manually load them from a crosh shell with:
```
$ sudo /sbin/insmod /usr/local/modules/x86_64_3.8.11/cifs.ko
$ sudo /sbin/insmod /usr/local/modules/x86_64_3.8.11/md4.ko
```
then you can mount from the command line in the chroot your smb share with the mount command. 
If I have some time I will build the autofs and nfs modules. Be aware that modules can be easily adjusted to have malicious code, so don't just blindly accept them from anyone. This is one of the reasons I didn't setup something where chromeos modules can be shared. I can't control how other people will build there modules. 99.9% they will be sincere, but that 0.1% will be hard to pick out and can cause a lot of damage.

**Comment by divx118** [comment]
@VeronicaEC Updated the script, so it creates external devices in the chromeos Files app with the name you specified in fstab as mount point. These devices will also turn up in the file manager of your chroot. If you want to unmount them then you can do that in the chromeos Files app by clicking the eject button. Unmounting will not work from inside a chroot.  
So there is no need anymore to use external media USB sticks or SD-cards. It is however still possible, if the mount point starts with a / it will try to mount on the directory specified.

The [README.md](https://github.com/divx118/cifs/blob/master/README.md) is updated. You only need to follow the steps below again and edit your /usr/local/etc/fstab file.
```
$ cd /usr/local 
$ sudo wget "https://raw.github.com/divx118/cifs/master/mountcifs.tar.gz" 
$ sudo tar xvf mountcifs.tar.gz 
```

NOTE: the code is roughly tested and I didn't find any issues, if you find some just create a new issue.

**Comment by VeronicaEC** [comment]
Thank you, tested both solutions and both worked as expected, no issues so far.

**Comment by divx118** [comment]
Closing this issue. Thanks for reporting back.
